name: Build GL-iNet

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-glinet.yml
      - profiles/gl-infra-builder/**/*
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: false
        type: boolean
      clean:
        description: 'clean cache'
        required: false
        default: false
        type: boolean
      profile:
        type: choice
        description: 选择配置
        default: '["gl-axt1800"]'
        options:
          - '["gl-axt1800"]'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Build ${{matrix.profile}}
    strategy:
      fail-fast: false
      matrix:
        profile: ${{ fromJSON( github.event.inputs.profile || '["acrh17-lienol-2102"]') }}

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install build-essential libncurses5-dev gawk git libssl-dev gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools python3-yaml

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone OpenWrt Builder Repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@github.com"
        git clone https://github.com/gl-inet/gl-infra-builder.git
        cd gl-infra-builder

        mkdir feeds/fullconenat
        git clone -b master https://github.com/LGA1150/openwrt-fullconenat feeds/fullconenat/fullconenat

        python3 setup.py -c configs/config-wlan-ap.yml
        cd wlan-ap/openwrt

        # remove duplicate package
        rm -rf immortalwrt_luci/applications/luci-app-acl
        rm -rf immortalwrt_luci/applications/luci-app-acme
        rm -rf immortalwrt_luci/applications/luci-app-adblock
        rm -rf immortalwrt_luci/applications/luci-app-advanced-reboot
        rm -rf immortalwrt_luci/applications/luci-app-ahcp
        rm -rf immortalwrt_luci/applications/luci-app-aria2
        rm -rf immortalwrt_luci/applications/luci-app-attendedsysupgrade
        rm -rf immortalwrt_luci/applications/luci-app-babeld
        rm -rf immortalwrt_luci/applications/luci-app-banip
        rm -rf immortalwrt_luci/applications/luci-app-bcp38
        rm -rf immortalwrt_luci/applications/luci-app-bmx7
        rm -rf immortalwrt_luci/applications/luci-app-clamav
        rm -rf immortalwrt_luci/applications/luci-app-commands
        rm -rf immortalwrt_luci/applications/luci-app-coovachilli
        rm -rf immortalwrt_luci/applications/luci-app-cshark
        rm -rf immortalwrt_luci/applications/luci-app-dawn
        rm -rf immortalwrt_luci/applications/luci-app-dcwapd
        rm -rf immortalwrt_luci/applications/luci-app-ddns
        rm -rf immortalwrt_luci/applications/luci-app-diag-core
        rm -rf immortalwrt_luci/applications/luci-app-dnscrypt-proxy
        rm -rf immortalwrt_luci/applications/luci-app-dockerman
        rm -rf immortalwrt_luci/applications/luci-app-dump1090
        rm -rf immortalwrt_luci/applications/luci-app-dynapoint
        rm -rf immortalwrt_luci/applications/luci-app-eoip
        rm -rf immortalwrt_luci/applications/luci-app-firewall
        rm -rf immortalwrt_luci/applications/luci-app-frpc
        rm -rf immortalwrt_luci/applications/luci-app-frps
        rm -rf immortalwrt_luci/applications/luci-app-fwknopd
        rm -rf immortalwrt_luci/applications/luci-app-hd-idle
        rm -rf immortalwrt_luci/applications/luci-app-https-dns-proxy
        rm -rf immortalwrt_luci/applications/luci-app-ksmbd
        rm -rf immortalwrt_luci/applications/luci-app-ledtrig-rssi
        rm -rf immortalwrt_luci/applications/luci-app-ledtrig-switch
        rm -rf immortalwrt_luci/applications/luci-app-ledtrig-usbport
        rm -rf immortalwrt_luci/applications/luci-app-ltqtapi
        rm -rf immortalwrt_luci/applications/luci-app-lxc
        rm -rf immortalwrt_luci/applications/luci-app-minidlna
        rm -rf immortalwrt_luci/applications/luci-app-mjpg-streamer
        rm -rf immortalwrt_luci/applications/luci-app-mosquitto
        rm -rf immortalwrt_luci/applications/luci-app-mwan3
        rm -rf immortalwrt_luci/applications/luci-app-nextdns
        rm -rf immortalwrt_luci/applications/luci-app-nft-qos
        rm -rf immortalwrt_luci/applications/luci-app-nlbwmon
        rm -rf immortalwrt_luci/applications/luci-app-ntpc
        rm -rf immortalwrt_luci/applications/luci-app-nut
        rm -rf immortalwrt_luci/applications/luci-app-ocserv
        rm -rf immortalwrt_luci/applications/luci-app-olsr
        rm -rf immortalwrt_luci/applications/luci-app-olsr-services
        rm -rf immortalwrt_luci/applications/luci-app-olsr-viz
        rm -rf immortalwrt_luci/applications/luci-app-omcproxy
        rm -rf immortalwrt_luci/applications/luci-app-openvpn
        rm -rf immortalwrt_luci/applications/luci-app-opkg
        rm -rf immortalwrt_luci/applications/luci-app-p910nd
        rm -rf immortalwrt_luci/applications/luci-app-pagekitec
        rm -rf immortalwrt_luci/applications/luci-app-polipo
        rm -rf immortalwrt_luci/applications/luci-app-privoxy
        rm -rf immortalwrt_luci/applications/luci-app-qos
        rm -rf immortalwrt_luci/applications/luci-app-radicale
        rm -rf immortalwrt_luci/applications/luci-app-radicale2
        rm -rf immortalwrt_luci/applications/luci-app-rp-pppoe-server
        rm -rf immortalwrt_luci/applications/luci-app-samba4
        rm -rf immortalwrt_luci/applications/luci-app-ser2net
        rm -rf immortalwrt_luci/applications/luci-app-shadowsocks-libev
        rm -rf immortalwrt_luci/applications/luci-app-shairplay
        rm -rf immortalwrt_luci/applications/luci-app-siitwizard
        rm -rf immortalwrt_luci/applications/luci-app-simple-adblock
        rm -rf immortalwrt_luci/applications/luci-app-smartdns
        rm -rf immortalwrt_luci/applications/luci-app-snmpd
        rm -rf immortalwrt_luci/applications/luci-app-softether
        rm -rf immortalwrt_luci/applications/luci-app-splash
        rm -rf immortalwrt_luci/applications/luci-app-sqm
        rm -rf immortalwrt_luci/applications/luci-app-squid
        rm -rf immortalwrt_luci/applications/luci-app-statistics
        rm -rf immortalwrt_luci/applications/luci-app-tinyproxy
        rm -rf immortalwrt_luci/applications/luci-app-transmission
        rm -rf immortalwrt_luci/applications/luci-app-travelmate
        rm -rf immortalwrt_luci/applications/luci-app-ttyd
        rm -rf immortalwrt_luci/applications/luci-app-udpxy
        rm -rf immortalwrt_luci/applications/luci-app-uhttpd
        rm -rf immortalwrt_luci/applications/luci-app-unbound
        rm -rf immortalwrt_luci/applications/luci-app-upnp
        rm -rf immortalwrt_luci/applications/luci-app-vnstat
        rm -rf immortalwrt_luci/applications/luci-app-vnstat2
        rm -rf immortalwrt_luci/applications/luci-app-vpn-policy-routing
        rm -rf immortalwrt_luci/applications/luci-app-vpnbypass
        rm -rf immortalwrt_luci/applications/luci-app-watchcat
        rm -rf immortalwrt_luci/applications/luci-app-wifischedule
        rm -rf immortalwrt_luci/applications/luci-app-wireguard
        rm -rf immortalwrt_luci/applications/luci-app-wol
        rm -rf immortalwrt_luci/applications/luci-app-xinetd
        rm -rf immortalwrt_luci/applications/luci-app-yggdrasil
        rm -rf immortalwrt_luci/collections/luci
        rm -rf immortalwrt_luci/collections/luci-lib-docker
        rm -rf immortalwrt_luci/collections/luci-light
        rm -rf immortalwrt_luci/collections/luci-nginx
        rm -rf immortalwrt_luci/collections/luci-ssl
        rm -rf immortalwrt_luci/collections/luci-ssl-nginx
        rm -rf immortalwrt_luci/collections/luci-ssl-openssl
        rm -rf immortalwrt_luci/contrib/package/csstidy
        rm -rf immortalwrt_luci/contrib/package/lucihttp
        rm -rf immortalwrt_luci/libs/luci-lib-base
        rm -rf immortalwrt_luci/libs/luci-lib-httpclient
        rm -rf immortalwrt_luci/libs/luci-lib-httpprotoutils
        rm -rf immortalwrt_luci/libs/luci-lib-ip
        rm -rf immortalwrt_luci/libs/luci-lib-ipkg
        rm -rf immortalwrt_luci/libs/luci-lib-iptparser
        rm -rf immortalwrt_luci/libs/luci-lib-json
        rm -rf immortalwrt_luci/libs/luci-lib-jsonc
        rm -rf immortalwrt_luci/libs/luci-lib-nixio
        rm -rf immortalwrt_luci/libs/luci-lib-px5g
        rm -rf immortalwrt_luci/libs/luci-lib-rpcc
        rm -rf immortalwrt_luci/libs/rpcd-mod-luci
        rm -rf immortalwrt_luci/libs/rpcd-mod-rad2-enc
        rm -rf immortalwrt_luci/libs/rpcd-mod-rrdns
        rm -rf immortalwrt_luci/modules/luci-base
        rm -rf immortalwrt_luci/modules/luci-compat
        rm -rf immortalwrt_luci/modules/luci-mod-admin-full
        rm -rf immortalwrt_luci/modules/luci-mod-admin-mini
        rm -rf immortalwrt_luci/modules/luci-mod-battstatus
        rm -rf immortalwrt_luci/modules/luci-mod-dashboard
        rm -rf immortalwrt_luci/modules/luci-mod-network
        rm -rf immortalwrt_luci/modules/luci-mod-rpc
        rm -rf immortalwrt_luci/modules/luci-mod-status
        rm -rf immortalwrt_luci/modules/luci-mod-system
        rm -rf immortalwrt_luci/protocols/luci-proto-3g
        rm -rf immortalwrt_luci/protocols/luci-proto-bonding
        rm -rf immortalwrt_luci/protocols/luci-proto-gre
        rm -rf immortalwrt_luci/protocols/luci-proto-hnet
        rm -rf immortalwrt_luci/protocols/luci-proto-ipip
        rm -rf immortalwrt_luci/protocols/luci-proto-ipv6
        rm -rf immortalwrt_luci/protocols/luci-proto-modemmanager
        rm -rf immortalwrt_luci/protocols/luci-proto-ncm
        rm -rf immortalwrt_luci/protocols/luci-proto-openconnect
        rm -rf immortalwrt_luci/protocols/luci-proto-openfortivpn
        rm -rf immortalwrt_luci/protocols/luci-proto-ppp
        rm -rf immortalwrt_luci/protocols/luci-proto-pppossh
        rm -rf immortalwrt_luci/protocols/luci-proto-qmi
        rm -rf immortalwrt_luci/protocols/luci-proto-relay
        rm -rf immortalwrt_luci/protocols/luci-proto-sstp
        rm -rf immortalwrt_luci/protocols/luci-proto-vpnc
        rm -rf immortalwrt_luci/protocols/luci-proto-vxlan
        rm -rf immortalwrt_luci/protocols/luci-proto-wireguard
        rm -rf immortalwrt_luci/themes/luci-theme-bootstrap
        rm -rf immortalwrt_luci/themes/luci-theme-material
        rm -rf immortalwrt_luci/themes/luci-theme-openwrt
        rm -rf immortalwrt_luci/themes/luci-theme-openwrt-2020
        rm -rf kenzok8_packages/adguardhome
        rm -rf kenzok8_packages/luci-app-dockerman
        rm -rf kenzok8_packages/luci-app-smartdns
        rm -rf kenzok8_packages/luci-lib-ipkg
        rm -rf kenzok8_packages/smartdns
        rm -rf small_package/adguardhome
        rm -rf small_package/aria2
        rm -rf small_package/ariang
        rm -rf small_package/cgroupfs-mount
        rm -rf small_package/coremark
        rm -rf small_package/ddns-scripts
        rm -rf small_package/dockerd
        rm -rf small_package/haproxy
        rm -rf small_package/luci-app-dockerman
        rm -rf small_package/luci-app-nft-qos
        rm -rf small_package/luci-app-smartdns
        rm -rf small_package/luci-app-snmpd
        rm -rf small_package/luci-app-watchcat
        rm -rf small_package/luci-lib-ipkg
        rm -rf small_package/miniupnpd
        rm -rf small_package/msmtp
        rm -rf small_package/mwan3
        rm -rf small_package/netdata
        rm -rf small_package/nft-qos
        rm -rf small_package/nginx
        rm -rf small_package/rp-pppoe
        rm -rf small_package/shadowsocks-libev
        rm -rf small_package/smartdns
        rm -rf small_package/tailscale
        rm -rf small_package/transmission-web-control
        rm -rf small_package/uwsgi
        rm -rf small_package/watchcat
        rm -rf small_package/xray-core

        # patch FULLCONENAT
        mkdir package/network/config/firewall/patches
        wget -P package/network/config/firewall/patches/ https://github.com/LGA1150/fullconenat-fw3-patch/raw/master/fullconenat.patch

        git clone https://github.com/gl-inet/glinet4.x.git
        cp ./glinet4.x/pkg_config/gl_pkg_config_axt1800.mk  ./glinet4.x/ipq60xx/gl_pkg_config.mk
        # cp ./glinet4.x/pkg_config/glinet_depends_axt1800.yml  ./profiles/glinet_depends.yml
        rm ./glinet4.x/ipq60xx/gl-sdk4-luci*.ipk
        mkdir -p profiles/kltk
        cp $GITHUB_WORKSPACE/profiles/gl-infra-builder/*.yml ./profiles/kltk/

        ./scripts/gen_config.py kltk/glinet-axt1800

    - name: show config
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        echo ::group::diffconfig
        ./scripts/diffconfig.sh
        echo ::endgroup::
        echo ::group::config
        cat .config
        echo ::endgroup::

    - name: Download packages
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        make download -j8 || make download -j1 V=s

    - name: Compile the firmware
      id: compile
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        make -j$(nproc) GL_PKGDIR=`pwd`/glinet4.x/ipq60xx || make -j1 V=s GL_PKGDIR=`pwd`/glinet4.x/ipq60xx
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
        path: gl-infra-builder/wlan-ap/openwrt/bin/targets/ipq807x/ipq60xx/openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz

    - name: Organize files
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        find bin -iname '*.apk' -delete
        rm -f bin/targets/ipq807x/ipq60xx/openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
        cp .config bin/targets/ipq807x/ipq60xx/config

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: OpenWrt_bin
        path: gl-infra-builder/wlan-ap/openwrt/bin
