name: Build GL-iNet

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-glinet.yml
      - profiles/gl-infra-builder/**/*
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: false
        type: boolean
      clean:
        description: 'clean cache'
        required: false
        default: false
        type: boolean
      profile:
        type: choice
        description: 选择配置
        default: '["gl-axt1800"]'
        options:
          - '["gl-axt1800"]'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Build ${{matrix.profile}}
    strategy:
      fail-fast: false
      matrix:
        profile: ${{ fromJSON( github.event.inputs.profile || '["acrh17-lienol-2102"]') }}

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install build-essential libncurses5-dev gawk git libssl-dev gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools python3-yaml

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone OpenWrt Builder Repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@github.com"
        git clone https://github.com/gl-inet/gl-infra-builder.git
        cd gl-infra-builder

        mkdir feeds/fullconenat
        git clone -b master https://github.com/LGA1150/openwrt-fullconenat feeds/fullconenat/fullconenat

        python3 setup.py -c configs/config-wlan-ap.yml
        cd wlan-ap/openwrt

        # patch FULLCONENAT
        mkdir package/network/config/firewall/patches
        wget -P package/network/config/firewall/patches/ https://github.com/LGA1150/fullconenat-fw3-patch/raw/master/fullconenat.patch

        git clone https://github.com/gl-inet/glinet4.x.git
        cp ./glinet4.x/pkg_config/gl_pkg_config_axt1800.mk  ./glinet4.x/ipq60xx/gl_pkg_config.mk
        # cp ./glinet4.x/pkg_config/glinet_depends_axt1800.yml  ./profiles/glinet_depends.yml
        rm ./glinet4.x/ipq60xx/gl-sdk4-luci*.ipk
        mkdir -p profiles/kltk
        cp $GITHUB_WORKSPACE/profiles/gl-infra-builder/*.yml ./profiles/kltk/

        ./scripts/gen_config.py kltk/glinet-axt1800

    - name: show config
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        echo ::group::diffconfig
        ./scripts/diffconfig.sh
        echo ::endgroup::
        echo ::group::config
        cat .config
        echo ::endgroup::

    - name: Download packages
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        make download -j8 || make download -j1 V=s

    - name: Compile the firmware
      id: compile
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        make -j$(nproc) GL_PKGDIR=`pwd`/glinet4.x/ipq60xx || make -j1 V=s GL_PKGDIR=`pwd`/glinet4.x/ipq60xx
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
        path: gl-infra-builder/wlan-ap/openwrt/bin/targets/ipq807x/ipq60xx/openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz

    - name: Organize files
      run: |
        cd gl-infra-builder/wlan-ap/openwrt
        find bin -iname '*.apk' -delete
        rm -f bin/targets/ipq807x/ipq60xx/openwrt-imagebuilder-ipq807x-ipq60xx.Linux-x86_64.tar.xz
        cp .config bin/targets/ipq807x/ipq60xx/config

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: OpenWrt_bin
        path: gl-infra-builder/wlan-ap/openwrt/bin
